version: "3.9"  # optional since v1.27.0
services:
  node-backend:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on: 
      - mongo
    command: node index.js
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: